### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by u20772077**
NRF call for students 2022

### CODE REVIEW

**Review by vukosim — CHANGES_REQUESTED** [review]
@u20772077 There is no front matter on this. Remember it must have that little snippet at the beginning of each post.

**Comment by u20772077** [comment]
Referring to that small table?


Sent from Mail for Windows 10

**Comment by vukosim** [comment]
Yes

**Comment by u20772077** [comment]
Alright , can I use the NRF images I have or do are you going to send me specific ones?

Sent from Mail for Windows 10

**Comment by u20772077** [comment]
My apologies doc,  I thought I had images. I only have pdf docs.

Sent from Mail for Windows 10

**Comment by vukosim** [comment]
Dont worry about images for this one.

**Pull request merged**
